version: "3"

services:

  mysql:
    container_name: ${LABDSOFT_DB_HOST}
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${LABDSOFT_DB_DEV_DB_NAME}
      - MYSQL_USER=${LABDSOFT_DB_USER}
      - MYSQL_PASSWORD=${LABDSOFT_DB_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  labdsof-api:
    container_name: labdsoft-api
    build: ./
    ports:
    - "9092:9092"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - LABDSOFT_DB_USER=${LABDSOFT_DB_USER}
      - LABDSOFT_DB_PASS=${LABDSOFT_DB_PASS}
      - LABDSOFT_DB_HOST=${LABDSOFT_DB_HOST}
      - LABDSOFT_DB_DEV_DB_NAME=${LABDSOFT_DB_DEV_DB_NAME}
      - OPEN_API_KEY=${OPEN_API_KEY}

  labdsof-flutter:
    container_name: labdsoft-flutter
    build: ./public
    ports:
    - "5173:5173"
    depends_on:
    - labdsof-api

networks:
  Smart_city:
    driver: bridge
