# secret.yaml for sensitive environment variables
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHB3ZA==
  LABDSOFT_DB_PASS: MTIzNDU2Nzg5
  LABDSOFT_DB_USER: c21hcnRfdXNlcg==
  LABDSOFT_APP_SECRET: ZGVmYXVsdGFwcHNlY3JldA==
  LABDSOFT_DB_HOST: bXlzcWwtc3Zj
  LABDSOFT_DB_DEV_DB_NAME: ZGF0YV9sYWJkc29mdA==
  OPEN_API_KEY: WU9VUl9BQ1RVQUxfQVBJX0tFWQ==
  
