on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

name: release-please-with-apk

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # You will want to configure a GitHub Actions secret with a
          # Personal Access Token if you want GitHub Actions CI
          # checks to run on Release Please PRs.
          # The folowing assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          #token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

          # if you dont need to trigger new workflow runs on a release please PR
          # its fine to use GITHUB_TOKEN as folows
          token: ${{ secrets.GITHUB_TOKEN }}

          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
          package-name: labdsoft-project

  lintFrontEnd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: ./public/android/app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Install Ionic
        run: npm install -g @ionic/cli
        working-directory: ./

      - name: Install dependencies
        run: npm install
        working-directory: ./public

      - name: Sync ionic in production
        run: ionic cap sync
        working-directory: ./public

      - name: Give gradlew execution permission
        run: chmod +x gradlew
        working-directory: ./public/android

      - name: Check for Gradle wrapper JAR
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper JAR not found. Regenerating wrapper..."
            ./gradlew wrapper
          fi
        working-directory: ./public/android

      - name: Build debug release with gradle
        run: ./gradlew assembleDebug
        working-directory: ./public/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./public/android/app/build/outputs/apk/debug

  uploadAPK:
    runs-on: ubuntu-latest
    needs: [lintFrontEnd, release-please]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: ./public/android/app/build/outputs/apk/debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./public/android/app/build/outputs/apk/debug
